server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type: TRACE

#App Properties
magly:
  app:
    jwtSecret: jwtBaguvixHesoyam
    jwtExpiration: 86400